# Generated by Django 4.2.5 on 2023-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Employee_Id', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('No_of_Leaves', models.BigIntegerField()),
                ('Balance_Leaves', models.BigIntegerField()),
            ],
        ),
    ]
