# Generated by Django 5.0 on 2024-02-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0005_leave_delete_employee_delete_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='Emp_id',
            field=models.CharField(default='your_default_value', max_length=20),
        ),
    ]
