# Generated by Django 4.2.5 on 2024-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0006_leave_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='Emp_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
