# Generated by Django 4.2.5 on 2024-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0007_alter_leave_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='Emp_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Successfully applied', max_length=30),
        ),
    ]
